### ISSUE TITLE
iOS sync only works after closing app entirely

### ISSUE THREAD

**Issue by geoffwild11** [HabitRPG/habitrpg-mobile#185]
If I make changes on my computer they don't sync to the app on iOS unless I completely close the app. Any way to fix that sync?

**Comment by crookedneighbor** [comment]
I'm closing this because not only has the app changed significantly since it was opened, but we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).
