### ISSUE TITLE
iOS app version 2 caused death before sync

### ISSUE THREAD

**Issue by stuckfly** [HabitRPG/habitrpg-mobile#207]
Logged in on my computer and had died (legitimately). Health at max, did a few tasks to get XP up. Short while later launched the new mobile app on iOS and it said I died. I assumed it was referring to my earlier death, but when I got home I had died a second time. So, I guess things didn't sync immediately when I opened the mobile app and it didn't know I'd already died and lost gold etc? Seems like a bug to me

**Comment by crookedneighbor** [comment]
I'm closing this because not only has the app changed significantly since it was opened, but we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon.
