### ISSUE TITLE
Building for BlackBerry 10

### ISSUE THREAD

**Issue by davehong** [HabitRPG/habitrpg-mobile#208]
Creating a thread for anyone interested in building a BB10 native version of HabitRPG.

I'd be happy to help facilitate (and maybe be more of an active contributor when time permits). :)

Thanks to fragmental for inspiring me to do this, since he/she created #141 for Windows Phone development.

**Comment by davehong** [comment]
@crookedneighbor ...is this closed just because this is low-priority, or does it belong somewhere else? Let me know! :cat:

**Comment by crookedneighbor** [comment]
@davehong I closed it because  we're working on native apps and will not be adding any new features to the phonegap app. It will be deprecated soon.

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)

We don't have the resources to dedicate any devs to build/maintain a blackberry app, but if you'd like to build an app for Blackberry, you can add it to the wiki!

**Comment by cmmata** [comment]
@crookedneighbor What about using the Angular part of this phonegap app? I think it's still possible to develop web apps that look like native in BB10. Next month I'll take a look, and if I see it's possible and not too difficult for me, I'll try to port it. If you agree and let me take this code as the starting point of course :)

If I finally do it, where should I add in the wiki? In [apps page](http://habitica.wikia.com/wiki/Category:Apps)?

**Comment by davehong** [comment]
Thanks for the reply @crookedneighbor !

At this point, it's probably not worth the effort to make a native BB10 app - BlackBerry bundles the Android Appstore in their new BlackBerrys, and it's trivial to run an Android app on those devices.

**Comment by cmmata** [comment]
Blackberry bundles Amazon Appstore, not Google Play. So there will be no need if the app is uploaded to both stores, if it's uploaded only to Google Play you'll need to get the APK, or install snap and download from there.

Anyway, I think Google Play Services can't work on BlackBerry devices, so if Android app uses any of Google's libraries, there will be some parts of the app that won't run.
