### ISSUE TITLE
UI - When editing a task/daily/etc the back button and the menu button are visable

### ISSUE THREAD

**Issue by joewashear007** [HabitRPG/habitrpg-mobile#209]
This might be a nit picky thing, but I don't think the slide menu show be active when editing something. It disrupts the flow of the app and look bad. 

I don't know all that much about jade, but this "should" be easy to fix.

![screenshot_2014-05-13-13-25-15](https://cloud.githubusercontent.com/assets/3577785/2961155/b48b2166-dac3-11e3-8a5d-9d8499cecb0e.png)

**Comment by crookedneighbor** [comment]
I'm closing this because not only has the app changed significantly since it was opened, but we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon.
