### ISSUE TITLE
iOS - Both iPhone and iPad app design very different from screenshots

### ISSUE THREAD

**Issue by nchpmn** [HabitRPG/habitrpg-mobile#211]
There seems to be a very large difference between the screenshots on the App Store and what is actually displayed in the app. The below screenshots are what is displayed for me.

![photo 1](https://cloud.githubusercontent.com/assets/385808/3009092/c110224a-dee4-11e3-89f0-9f0be03e8f93.PNG)

![photo 2](https://cloud.githubusercontent.com/assets/385808/3009093/c112c8ec-dee4-11e3-920a-9376a3d6e895.PNG)

I've tried crashing and reopening the app, as well as redownloading from the Store.

Unfortunately, I'm no iOS developer, so I can't pinpoint a potential reason. Also, I haven't seen anyone else talking about this issue, so... has anyone else experienced it?

I'm using an iPhone 4S/iPad 2 WiFi, both running 6.1.3, which is listed as supported. I can see the Store page states it was "designed for iPhone 5", but this shouldn't make a difference on this scale, should it?

**Comment by crookedneighbor** [comment]
I'm closing this because not only has the app changed significantly since it was opened, but we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon.
