### ISSUE TITLE
Notification for due remainders

### ISSUE THREAD

**Issue by Petemir** [HabitRPG/habitrpg-mobile#212]
This is a suggestion for a feature, maybe it would be possible in iOS/Android to show in the notifications bars reminders for the ToDos that are near due-date?

**Comment by crookedneighbor** [comment]
I'm closing this because we're currently working on native apps and will not be adding any new features to the phonegap app.

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
