### ISSUE TITLE
Back button leaves program

### ISSUE THREAD

**Issue by fragmental** [HabitRPG/habitrpg-mobile#221]
The back button, on the phone, leaves the program.  Perhaps this is intentional behavior, but from using other programs, I usually expect the back button to either return to my previous page, or ask me if I would like to leave the program.

This is further aggravated by the 7+ second load time for the app. #218

Mostly it just gives me 7 seconds to feel stupid for accidentally closing the app again.

**Comment by crookedneighbor** [comment]
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
