### ISSUE TITLE
Android app Rewards screen shows gear for Level 1

### ISSUE THREAD

**Issue by stumo** [HabitRPG/habitrpg-mobile#236]
The Rewards screen on the app shows various gear options, even when they aren't available on the main website e.g. for a L1 character.

Just starting out, so difficult to know what there should and shouldn't be here, but I can get rainbow armour/helmet, both for zero gold.

**Comment by crookedneighbor** [comment]
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
