### ISSUE TITLE
Dragging items doesn't work very well on Android and IOS

### ISSUE THREAD

**Issue by willsheppard** [HabitRPG/habitrpg-mobile#265]
When I touch the three lines on a habit/daily item, they change colour to indicate I've selected it, but dragging down has no effect. After the third or fourth try, dragging works. Sometimes clicking off/on the 4-arrows move control makes it work better.

Also (different issue) when I am eventually dragging an item, the screen starts to scroll and just keeps going, even though I've stopped pulling off the edge of the screen. It's like the screen is very heavy and has too much momentum. Please lighten the screen's virtual weight!

And finally (feature request) when I drag a habit or daily, it needs to just swap places with the item above/below it, not float over the top. Currently I'm always placing it one too high/low. With this change it would always be obvious where it would end up when I stop dragging.

P.S. fantastic app/concept

Nexus 5
Android 4.4.4
HabitRPG 0.0.35

**Comment by crookedneighbor** [comment]
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
