### ISSUE TITLE
When opening items, I don't see any edit options, just a white page (fixed by restarting)

### ISSUE THREAD

**Issue by willsheppard** [HabitRPG/habitrpg-mobile#266]
It worked fine yesterday, the day I installed it. Today when I touch on a habit/daily/todo/reward, I don't see any settings, just the header "<Habits = Details" text, and the rest of the screen is blank white.

Swipe-closing the app from the task list did not fix it. Force stopping *did* fix it.

Nexus 5
Android 4.4.4
HabitRPG 0.0.35

**Comment by crookedneighbor** [comment]
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
