### ISSUE TITLE
Edit saving button not clear

### ISSUE THREAD

**Issue by Kitiki** [HabitRPG/habitrpg-mobile#272]
Edits on dailies and habits are not saving even if I manually refresh. 
 When I close out the app completely and reopen it, I see the edits, it auto refreshes and the edits disappear. 
iOS 7.1.2

**Comment by crookedneighbor** [comment]
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
