### ISSUE TITLE
[iPhone iOS 8.2] Can not set Saturday and Sundays for repeating Dailies task & Overlap of buttons

### ISSUE THREAD

**Issue by ckylee** [HabitRPG/habitrpg-mobile#276]
![img_0209](https://cloud.githubusercontent.com/assets/8842929/4540508/a58b68b6-4e08-11e4-827b-bc71d583c7f2.PNG)

There are two problems:

1. There only seems to be Monday-Friday option for setting repetitive schedules. (What is ... ?)

2. The check icon over laps with the text 'Details'

**Comment by crookedneighbor** [comment]
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
