### ISSUE TITLE
Textwrap premature

### ISSUE THREAD

**Issue by goldfndr** [HabitRPG/habitrpg-mobile#277]
On my Moto G (720x1280, ~329 ppi), as of v0.0.36 and the previous version, short lines of text that ought to fit are being wrapped. I can work around it somewhat by putting an emoji between words or by making a word **bold**. The wrapping is identical in both portrait and landscape, see below; note that "Water garden" is the text at the top of the screenshot.
![screenshot_2014-10-08-10-36-45](https://cloud.githubusercontent.com/assets/173956/4571730/6b40ea58-4f7c-11e4-90ae-4462356e4536.png)

The length of the text in both characters and pixels doesn't seem to matter; "Before shower" wraps while "Before breakfast" doesn't wrap. A longish description will take 2 lines, not 3 lines, but wrapping will be different on landscape vs portrait and the wrapping will be more sane.

Subtasks don't have the wrapping issue, but the wrapping is identical on the task detail page (e.g. "Clean your \n apartment", "1h Personal \n Project", "Use emojis \n :+1:").

I'm very new to HabitRPG (just started this week), so I've no idea if #205 might've had a side-effect.

**Comment by crookedneighbor** [comment]
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
