### ISSUE TITLE
Add task checkbox to task details view

### ISSUE THREAD

**Issue by goldfndr** [HabitRPG/habitrpg-mobile#278]
Each time I back out of a task's details page, the app (Android) scrolls to the top, and I need to find it again to check it off after completing the checklist items.

What'd be really handy is a checkbox to the left of the task's Title on the details page. Then I could check the Daily or To-Do off right there and not have to hunt it down again. Habits could have the +/- buttons on the right.

**Comment by crookedneighbor** [comment]
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
