### ISSUE TITLE
iOS 8 app not syncing properly

### ISSUE THREAD

**Issue by westenra** [HabitRPG/habitrpg-mobile#280]
I have the HabitRPG app on my phone, and certain To-Do items that I've already completed keep re-appearing. As well as this, I often get an "Error connecting to server" upon completing some tasks. What should I do? Will this glitch be fixed?

**Comment by crookedneighbor** [comment]
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
