### ISSUE TITLE
Description, Details, and interface for normal quests not showing up for The Moonstone Chain quest/quest scroll

### ISSUE THREAD

**Issue by Rbrinkley** [HabitRPG/habitrpg-mobile#281]
On the mobile app, the quest "The Moonstone Chain" is showing up with a blank text line and no response when pressed.The normal interface that pops up when you press on quest scrolls does not appear when you press on what I am assuming is the quest scroll for "the moonstone chain" since I can't see the text for the quest and I just recently got the quest since I am over level 60. 

Could anyone please fix this issue please?

![2014-10-24-16-38-54](https://cloud.githubusercontent.com/assets/7588148/4777684/4c324b10-5bd5-11e4-9903-c04e6953fa9d.png)

User id:6f14571c-f2e9-4446-8e4e-591a7a3a42eb

**Comment by crookedneighbor** [comment]
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
