### ISSUE TITLE
Party quest interface saying that the quest leader has left the party and can no longer begin the quest

### ISSUE THREAD

**Issue by Rbrinkley** [HabitRPG/habitrpg-mobile#282]
My party is currently ready to start a new quest. Specifically the quest "Help! Harpy!". And I came across this on mobile and was suprised. So I went onto the website and to my relief the quest owner was still in the party and the quest was still open for people to accept pending requests. I'm not sure if this is just an error for this quest but if someone could fix this issue I would greatly appreciate it. 

![party quest interface issue](https://cloud.githubusercontent.com/assets/7588148/4777751/82a1fafa-5bd6-11e4-8fcf-bd5cbf1e064a.png)

______________________
This is what appears on the website (Minus annotations). It says nothing about the current quest leader leaving the party:
----------------------------
![partyquestinterfaceissuewebsitecomparison](https://cloud.githubusercontent.com/assets/7588148/4784744/56fae0ee-5d64-11e4-8cc4-1035ec4ec913.png)

User id:6f14571c-f2e9-4446-8e4e-591a7a3a42eb

And again I can't seem to upload images onto github via mobile. Could someone please look into that?

**Comment by crookedneighbor** [comment]
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
