### ISSUE TITLE
level does not reset when I die

### ISSUE THREAD

**Issue by jacalata** [HabitRPG/habitrpg-mobile#284]
I have been flaky lately and so have died a few times. However, I have found that once I die, I am still 300 points away from the next level and i think my icon says level 12 still. This makes it pretty hard to get started again, and the text on death says I have been reset to level 1: should the xp to next level go back to about 50?

**Comment by crookedneighbor** [comment]
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
