### ISSUE TITLE
Items Checked on Mobile App Didn't Sync, Lost HP & Streaks

### ISSUE THREAD

**Issue by esquette** [HabitRPG/habitrpg-mobile#292]
I completed all my dailies yesterday and checked them off on my phone, but the boss quest still hit me, and I lost all the streaks that I didn't input directly to the computer.  Can I have my HP and streaks back?  Username: Esquette Email: s.e.hengeveld@gmail.com 

Thanks!

**Comment by crookedneighbor** [comment]
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
