### ISSUE TITLE
Bar colors for both Quest Bosses(Health) and player bars(Health, EXP, Mana in the Profile Tab) will sometimes overlap the text

### ISSUE THREAD

**Issue by Rbrinkley** [HabitRPG/habitrpg-mobile#294]
I noticed that sometimes when scrolling or just opening up the tab or page itself, the text for the health bars for quest bosses and all 3 bars for the player in the profile tab will be overlapped by the color of the bars themselves. I dont know if the quest bar error is just isolated to the quest "Help! Harpy", which was the quest I was doing at the time, or if all quest bosses are affected by this. Can someones please fix this?

__________________________________________________________________________

--------------------------------------------------------------------
"Help! Harpy!" Quest Boss health bar overlap:
------------------------------------------------------------------

![quest health bar text overlap](https://cloud.githubusercontent.com/assets/7588148/4912786/0c417562-64a4-11e4-9e70-bc9902950d3e.png)

_________________________________________________________________________

-------------------------------------------------------------------
Profile Tab- all 3 bars have text that is overlapped by the color of the bar:
--------------------------------------------------------------------

![profile tab health bar text overlap](https://cloud.githubusercontent.com/assets/7588148/4912787/27bf8324-64a4-11e4-9f50-02e73768875a.png)

________________________________________________________________________

User id:6f14571c-f2e9-4446-8e4e-591a7a3a42eb

**Comment by crookedneighbor** [comment]
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
