### ISSUE TITLE
Can't change order of To-Do List items

### ISSUE THREAD

**Issue by westenra** [HabitRPG/habitrpg-mobile#305]
Though I've changed the order of items on my To-Do list on the website, the app doesn't reflect these changes at all. Moreover, when I try to change the order of the items within the app, they snap back to the position they were in before once I exit "edit" mode or refresh the list. It's very frustrating.

**Comment by TheChumBucket** [comment]
There is a definite edit-sync bug on iOS. Try https://github.com/HabitRPG/habitrpg-mobile/issues/367, I found a trick that prevents loss of progress on my iPhone.

**Comment by crookedneighbor** [comment]
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
