### ISSUE TITLE
No place to enter ID/token (android)

### ISSUE THREAD

**Issue by talexand** [HabitRPG/habitrpg-mobile#306]
I downloaded the app from the Google store, punched in my server, user, and password, and got an 

> Alert: Please enter your ID and Token in settings.

when tapping Login.

`adb logcat` shows nothing related during this event.

Where am I supposed to enter the ID/token? There's nothing to slide, swipe, or tap to get a menu.

**Comment by crookedneighbor** [comment]
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
