### ISSUE TITLE
typing in text is way too slow on the mobile version

### ISSUE THREAD

**Issue by aleks-unity** [HabitRPG/habitrpg-mobile#307]
The app seems to be communicating to the internet for every keystroke, trying to synchronize, resulting in huge delays and almost unusable interface. It it especially slow, when there it no internet connection (!). Sometimes data gets lost if I type something in on a train, I'd like to still have it locally and synchronize later. 

Cheers
Aleks

**Comment by Sduibek** [comment]
Not sure if "me too" posts are useful here, but I get this as well. Sometimes it takes about 15 seconds for anything I typed to appear in the field when typing in a name for a new To-Do.

**Comment by aleks-unity** [comment]
After a few months of this, i stopped using the app. Good intention, bad
implementation, and apparently nobody cares enough to fix it

**Comment by Sduibek** [comment]
@aleks-unity I believe it's because they're working on making the apps native. PhoneGap by definition will usually be slower than native (i.e. coded in Java for Android and Swift/ObjC for iOS) apps.

I don't know this for a fact, I just think it makes sense -- switching to native code will make the apps more responsive, thus working to make the PhoneGap version more responsive when you're already working on native versions doesn't make sense.

**Comment by aleks-unity** [comment]
Just FYI the issue has not been adressed and the app is essentially
unusable on Android. I uninstalled it a few months ago.

**Comment by isaact-d** [comment]
Hi there, I'm definitely having this problem in the android app. When I input text when creating custom rewards the title text box is small and when I paste text into the box it takes a long time to respond If I want to edit the text in anyway swiping to the beginning of the text takes ages. If you just increased the text box size a lot of the lagging would stop

**Comment by crookedneighbor** [comment]
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
