### ISSUE TITLE
To-Do tasks not moving

### ISSUE THREAD

**Issue by aquagrunt** [HabitRPG/habitrpg-mobile#310]
I'm trying to rearrange my to do tasks and I have about 8 so I have to scroll to see some, but when I go to try to move my tasks down or up they won't go where I want them, sometimes it goes the whole wrong way. Please fix it or change it! Thanks!

**Comment by joho506** [comment]
Try going on desktop and deleting completed to-dos.

**Comment by crookedneighbor** [comment]
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
