### ISSUE TITLE
Possible: Decrease Size of Tasks

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitrpg-mobile#312]
Request from Trello:

"Make ionic-list elements in the mobile app smaller.

They're enormous. No one but those with the most improbably sized fingers wants list items this big. On my iPhone 6, my 4.7 inch screen allows me to see about 8 items at a time, while 12 could fit comfortably. I think this is the default ionic-list setting... it's just not a very good default.

I think the solution is to modify styles/ionic.app.scss, the file which overrides ionic styles, but it appears that even though that file exists, it isn't currently imported anywhere (presumably this should happen in a .jade file?). This is confusing and not my expertise and so I am here requesting that someone else consider doing it. It should be super easy for someone who understands ionic."

I'm not sure if the current size was chosen for accessibility issues so I'd like to hear from people before we commit to this.

Tagging @deilann in case he has insights.

**Comment by Sduibek** [comment]
Couldn't this be something customizable? i.e. a "Taks entry line height" in Settings.

**Comment by crookedneighbor** [comment]
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
