### ISSUE TITLE
Checklists disappearing in mobile app

### ISSUE THREAD

**Issue by Sophi007** [HabitRPG/habitrpg-mobile#314]
I have an ipad and laptop. When I create tasks and checklists on my ipad, the checklist disappears after I close the app. I've tried "syncing" by pulling down the tasks and letting it reload, but it doesn't work. After I create a task, the word Na NaN appear under the task. Could that have something to do with it?

Oh, and occasionally my ipad and laptop don't sync properly, but I know that's a common bug.

Here is my API in case it's needed: c8ab05a1-f5cd-4ef3-a67a-1cbdcf36f519
My ipad still has the old IOS. I haven't bothered to upload it to 8.1.2 yet. I don't know if that might be affecting it.

**Comment by TheChumBucket** [comment]
Try https://github.com/HabitRPG/habitrpg-mobile/issues/367. Making a checklist is editing, so this trick might solve your problem =) If you "sync" by pulling down, and the app doesn't sync, then you are definitely being affected by a bug. If you are able to, sync as often as you can. There are multiple bugs that can screw up syncing, but if you sync after every few actions (or after each action if it's not bothersome) you will not only minimize progress losses but can narrow down what bug is plaguing you =)

**Comment by crookedneighbor** [comment]
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
