### ISSUE TITLE
Text / icon overlap when in edit mode

### ISSUE THREAD

**Issue by himynameisoleg** [HabitRPG/habitrpg-mobile#316]
The title text and top right icons overlap. 
iPhone 5 -- iOS 8.1.2

**Comment by yanivefraim** [comment]
Hey,
What are the possibilities here? Can I make those icons smaller and closer to each other?
Thanks!

**Comment by crookedneighbor** [comment]
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
