### ISSUE TITLE
Sync previously written ToDo's

### ISSUE THREAD

**Issue by Thaenor** [HabitRPG/habitrpg-mobile#319]
I'm not sure whether this is a bug or if it's intended, but any todo's that I create while offline on my iphone (as any activity with the app) is erased with every sync.

For instance, I'm on my phone but I'm not connected to the Internet, I open the app, check a daily or two, and create a few ToDo's. Later when I connect and sync the app, the dailies become unchecked and the ToDo's are deleted.

*I'm not 100% sure but I think this also happens on android, but I'm using an iphone with the "official" app.*

**Comment by TheChumBucket** [comment]
Did you edit any items between syncs? Try https://github.com/HabitRPG/habitrpg-mobile/issues/367 if you edit anything on your mobile, even if you can't sync immediately. I would try that method offline, and then (before you make too much progress) try to sync online. You might be plagued by a completely different bug (then just ignore this post haha), but many people (including me) have lost progress due to the mobile edit-sync bug.

Don't fully exit the app between syncs (when you double-tap the home button, don't swipe the app to exit, leave it running in the background). Offline progress should be saved. I just did a test on my phone, using Airplane mode to simulate being offline. Opening the app while offline will not save progress. But (leave it running in the background the whole time) if you open the app online, go offline and make progress, then sync later online the progress is supposed to be saved =)

**Comment by Thaenor** [comment]
Actually, now the client doesn't even let me do any changes if I'm offline. Without an Internet connection I can tick any dailies or habits or even create them. The buttons simply don't do a thing.

**Comment by TheChumBucket** [comment]
That sucks. I'm sorry it won't work offline. Did you try to open it online, sync, then go offline? I was able to make changes offline, but only when I first opened it online and kept the app running in the background. If you did what I did and the app still ceases to function, I'm sorry that I couldn't help!

**Comment by Thaenor** [comment]
Nah... now I can't even create a new task when I'm offline. The button "add" simply does nothing. I need to connect to the Internet, sync and only then can i add the task.
It's kinda of a big feature for me because I'm always adding tasks on the go. The iOS Reminder does this just fine, I set a tasks, set a time to be reminded and it beeps just at the right time for me to remember the thing. It's just sad that it's not counting points for my Habit crusade.

**Comment by crookedneighbor** [comment]
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
