### ISSUE TITLE
App is scaled up on iPhone 6+

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitrpg-mobile#332]
I found this on Twitter but can't test directly:

> Feature req: App is scaled up on iPhone 6+ . I suspect you just have to add splash screens to get native resolution + keyboard
https://twitter.com/agius/status/557232247003037697

cc @negue

**Comment by negue** [comment]
oh.. thats bad, but I dont have any iPhone , nor a mac to help fix this issue :(

**Comment by crookedneighbor** [comment]
This might help: http://community.phonegap.com/nitobi/topics/app-auto-scaling-on-iphone-6-and-6-screens

**Comment by crookedneighbor** [comment]
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
