### ISSUE TITLE
cron reset twice in a day

### ISSUE THREAD

**Issue by stave24** [HabitRPG/habitrpg-mobile#333]
Hello everyone. So, I'm experiencing an issue with cron - it reset twice during the night resulting to massive hp loss. This happened again last week. Is there something you can do to fix that? 

My ID is : c7461f02-d081-4974-97c3-92e2c78af156

**Comment by crookedneighbor** [comment]
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
