### ISSUE TITLE
Super laggy

### ISSUE THREAD

**Issue by xanydee** [HabitRPG/habitrpg-mobile#337]
The last few weeks the android app has been super slow and laggy - it takes a couple minutes to respond once I've checked off a task, habit daily or try to do anything really. y I've tried using different phones,using data vs wifi, and uninstalling and reinstalling the app to no avail.

**Comment by blnk2010** [comment]
Same problem on both my android phone and tablet. Sometimes I have to wait a minute before I can even click on anything. That habit screen is also random at startup until I move to dailies and back to habits.

**Comment by cdhamman** [comment]
Same issue on Android phone. The app takes several seconds to respond after I tick off dailies and habits, and then the reward flashes too quickly for me to read. I don't mind the slow response time, but it would be nice if the reward notifications persisted longer. I never know how much gold and xp I get, or when I get item drops.

**Comment by Collagenus** [comment]
I dream of using HabitRPG as my primary To-Do App, but it's just too laggy!

**Comment by Sduibek** [comment]
Same here, I am on Android 4.3 and the app is consistently slow/laggy. I wonder if this is a side-effect of using PhoneGap?

**Comment by phortx** [comment]
In my experience the App was always extreme laggy. On my HTC Sensation it was nearly unusable, on the S3 mini of my girlfriend it's horrible laggy. On my HTC One M8 it's just slow. That's really annoying.

I think the reason is the technology stack used here, which has just a poor performance.

**Comment by andrewcamphouse** [comment]
Could be solved by visually marking the task as complete in the UI, then use a separate thread in the background to  perform the operation

**Comment by crookedneighbor** [comment]
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
