### ISSUE TITLE
Stats obscured in iOS mobile version after update

### ISSUE THREAD

**Issue by LeickR** [HabitRPG/habitrpg-mobile#342]
1) After the latest update, in the "Menu" view, the upper half of the avatar picture and stats is now obscured (by the bar that says "Menu").
2) if I pull down and hold, I can see the top of the picture. However, when I do this, sometimes the health and XP bars are blank, so I have to let it go and then pull down and hold again.

(Running HabitRPG v0.0.48 on an iPhone 6+, iOS version 8.1.3)

**Comment by negue** [comment]
I have the same issue sometimes on Android too :/

**Comment by crookedneighbor** [comment]
@LeickR the issue has also been reported here: https://github.com/HabitRPG/habitrpg/issues/4673

I know you were the first one to report it, but since the other issue has screenshots, I'm going to close this one and we'll use the other ticket to track the progress. If you'd like to get updates, you can go to the link provided above and choose the subscribe button.
