### ISSUE TITLE
Tasks are renamed on list after coming back sometimes

### ISSUE THREAD

**Issue by Andrelopithecus** [HabitRPG/habitrpg-mobile#344]
Sometimes when I open the menu, a task will have the same name as another task until I open that task and exit out of it again, which assigns it its correct name.

**Comment by blnk2010** [comment]
Does moving to a different screen, such as between habits and dailies then back to habits help?

**Comment by Andrelopithecus** [comment]
I don't believe I have encountered that before but, if i edit the task and then back out again it repopulates the correct name. I imagine going back between other menus might work as well.

**Comment by crookedneighbor** [comment]
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
