### ISSUE TITLE
Tags in Mobile?

### ISSUE THREAD

**Issue by hepiii** [HabitRPG/habitrpg-mobile#346]
Is anyone working on using tags in mobile?  It would be nice to have the ability to only see my errands when I'm out and about instead of having to scroll through a giant list to check off all the things I'm accomplishing.  :):)

Also I'm 100% new to github.  If I'm posting this in the wrong place, let me know.  Thanks!

**Comment by kyleb851** [comment]
I would also like to see this feature! I Don't want to have to use other clients on the Play Store for tags  :(

**Comment by cmmata** [comment]
I would like that feature too! +1

**Comment by TheChumBucket** [comment]
@cmmata I'm utterly new to Github. Is there anyway to +1 this page, or do I just "+1" in this comment?

**Comment by neoascetic** [comment]
@TheChumBucket on [Bountysource](https://www.bountysource.com/issues/8870753-tags-in-mobile) only for now. You also may use their browser extension.

**Comment by TheChumBucket** [comment]
@neoascetic TY for the info =)

**Comment by crookedneighbor** [comment]
I'm closing this because we're currently working on native apps and will not be adding any new features to the phonegap app.

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
