### ISSUE TITLE
Setting negative value for rewards possible.

### ISSUE THREAD

**Issue by Noctura** [HabitRPG/habitrpg-mobile#347]
However doing so damages you for the value typed in.

**Comment by crookedneighbor** [comment]
Related to: https://github.com/HabitRPG/habitrpg/issues/4018

**Comment by crookedneighbor** [comment]
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
