### ISSUE TITLE
Deleting the '1.' wich created a checklist, leaves a 'null' at To-Do description.

### ISSUE THREAD

**Issue by JaakUp** [HabitRPG/habitrpg-mobile#352]
Android LP 5.0.2
Habitrpg v 0.0.50

**Comment by crookedneighbor** [comment]
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
