### ISSUE TITLE
Dailies will not reset

### ISSUE THREAD

**Issue by kferd** [HabitRPG/habitrpg-mobile#353]
It's been a couple of days and the daily section has not been resetting it just stays checked all of the time is there any way to fix this?

**Comment by crookedneighbor** [comment]
Please see this issue for an explanation and fix: https://github.com/HabitRPG/habitrpg/issues/4742 or alternatively [HabitRPG Outage Instructions -> Unplanned Tavern Visit](http://habitrpg.wikia.com/wiki/HabitRPG_Outage_Instructions#Unplanned_Tavern_Visit) on the wiki. In brief, you need to check out of the Inn and then your Dailies will reset tomorrow (although those two links give you advice about how to force them to reset sooner if you wish to).

I'm closing this issue now since there isn't a bug any more, but if you have any questions, please do comment here! We will see your questions and we will answer them.
