### ISSUE TITLE
Character icon and health/experience meters obscured

### ISSUE THREAD

**Issue by cvesenka93** [HabitRPG/habitrpg-mobile#354]
Whenever I attempt to look at my character I need to scroll up and hold because the default location is above the top of the screen. I'm using an iPhone 6. This isn't game breaking but it sure as hell is annoying.

**Comment by PJay-** [comment]
Can you post a screenshot of it?

I think it would be fixed when https://github.com/HabitRPG/habitrpg-mobile/pull/349 is included in the update.

**Comment by lefnire** [comment]
This is an issue where iOS's status bar actually dips into the application's UI. Native iOS apps handle that automatically for you, but hybrid apps have to add extra padding on the top to prevent this. You can see how Ionic handles this here https://github.com/driftyco/ionic-starter-tabs/blob/master/js/app.js#L17tL20, which adds the necessary margin-top class when on iOS. We have this in our code just fine, and it used to work - I don't know if we need an Ionic upgrade due to recent iOS versions or what... Let me see if I can find a screenshot, they've been floating around as (duplicate) bug reports

**Comment by lefnire** [comment]
My bad, it's on the main repo ( @cvesenka93 did right by reporting it here) https://github.com/HabitRPG/habitrpg/issues/4673

**Comment by PJay-** [comment]
I don't have an iPhone so I'm curious whether it still occurs.

**Comment by lefnire** [comment]
Yeah, it would just be iPhone. Hopefully one of our mac users (or myself if i get around to it) can do iOS emulation (`gulp && cordova emulate ios`)

**Comment by cvesenka93** [comment]
Just took this screenshot, thanks for the quick response! Love the app,
this bug is just a little annoying.
cheers,

Chris

**Comment by PJay-** [comment]
https://github.com/HabitRPG/habitrpg-mobile/pull/356

Ignore H..., if you switch screens it changes to the full text

Current behaviour:

![screen shot 2015-03-12 at 23 15 33](https://cloud.githubusercontent.com/assets/2494146/6629440/4fcca15c-c90e-11e4-96e1-7362d7fda137.png)
![screen shot 2015-03-12 at 23 15 38](https://cloud.githubusercontent.com/assets/2494146/6629442/537e3ac2-c90e-11e4-9824-5d9ad9e6d02b.png)

Fixed behaviour:

![screen shot 2015-03-12 at 23 16 13](https://cloud.githubusercontent.com/assets/2494146/6629448/720ed8fc-c90e-11e4-88f2-085afc943283.png)
![screen shot 2015-03-12 at 23 16 17](https://cloud.githubusercontent.com/assets/2494146/6629449/7360bcde-c90e-11e4-9d4b-a01ca9196901.png)

**Comment by lurexus** [comment]
I experience this as well.
Using iPhone 6 Plus - iOS 8.2
See screenshot here: http://i.imgur.com/RnaQBLa.png

**Comment by crookedneighbor** [comment]
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
