### ISSUE TITLE
Boss not dying!

### ISSUE THREAD

**Issue by Kalfaris** [HabitRPG/habitrpg-mobile#357]
Two people in my party haven't had their 'attacks' on the boss come up. The boss should have died and we have all received the rewards for the quest but the bossis still there and we can't start a new quest.

**Comment by Alys** [comment]
Please tell us your unique user ID and the ID of your party. Unfortunately we have no way of helping without knowing that information. You can find out how to find those IDs from [Help menu (on the website) -> Report a Bug](https://github.com/HabitRPG/habitrpg/issues/2760) step 6.

Sorry about the delay in replying but we don't monitor the habitrpg-mobile issue queue in the same way as the main issue queue, because it is for mobile-specific issues. We'll keep this issue open now until we have fixed the problem you're having, but for future bug reports, could you please follow the [Help -> Report a Bug](https://github.com/HabitRPG/habitrpg/issues/2760) steps? That will put your issues into the best place for us to see them quickly.

**Comment by crookedneighbor** [comment]
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
