### ISSUE TITLE
abilities 

### ISSUE THREAD

**Issue by KagaKitsune** [HabitRPG/habitrpg-mobile#360]
Hay how can I use my abilities on the app. I am a mage but can't cast any of my spells from the app. I have to go to the site to do any of them.

**Comment by crookedneighbor** [comment]
@KagaKitsune It is not currently possible to access the spells from the mobile app, but you can use the browser on your phone to go to [habitrpg.com](https://habitrpg.com) where your spells will be accessible.

**Comment by Sduibek** [comment]
@crookedneighbor  Is this feature planned to be added? That seems like a pretty big omission.

**Comment by crookedneighbor** [comment]
Yes and no. We're moving to native iOS and Android apps instead of phone gap and the spells/skills will be able to be used in those versions. New features *will not be added* to the phone gap apps, but we'll try to fix bugs as we're able.

**Comment by Sduibek** [comment]
Fair enough, that sounds great. :)

**Comment by cmmata** [comment]
@crookedneighbor will those native apps be open source too? I don't see any repository like that in habitrpg/

**Comment by crookedneighbor** [comment]
@cmmata yes! Once the beta is ready to be released, they'll be available on Github for everyone to work on.

**Comment by cmmata** [comment]
@crookedneighbor perfect! Thank you! :+1:

**Comment by crookedneighbor** [comment]
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
