### ISSUE TITLE
Task attributes

### ISSUE THREAD

**Issue by cmmata** [HabitRPG/habitrpg-mobile#363]
Hello,

When I edit a task from mobile app, I can set difficulty, checklist, etc. but I can't set task attributes (physical, mental, ..). I have config option activated in web version and I can set attributes there, but I don't see how to do it in mobile version. Is there any way, or isn't it yet implemented?

I think this issue is not posted yet. If it's a duplicate sorry, didn't find it.

**Comment by TheChumBucket** [comment]
Do you mean Tags by attributes? There is also no way to sort any tasks (habits, dailies, to-dos) by a tag, so I believe tags simply haven't been implemented yet.

**Comment by crookedneighbor** [comment]
@TheChumBucket when you choose this option for stat allocation:

![screen shot 2015-06-07 at 10 14 33 pm](https://cloud.githubusercontent.com/assets/2916945/8027710/a9b3aae2-0d62-11e5-89ae-4e8526b328ce.png)

You get an additional item in the advanced options for a task:
![screen shot 2015-06-07 at 10 14 46 pm](https://cloud.githubusercontent.com/assets/2916945/8027712/b460c1f0-0d62-11e5-934f-61a820a4539f.png)

This is missing in the mobile app.

**Comment by TheChumBucket** [comment]
Ha, I was waaay off. Thank you for clearing up my misconception. Just like the Tags it is not implemented yet. If you can believe what I say lol.

**Comment by crookedneighbor** [comment]
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
