### ISSUE TITLE
Chocolate dissapeared from inventory after hatching a cactus. [Android 4.3]

### ISSUE THREAD

**Issue by Sduibek** [HabitRPG/habitrpg-mobile#364]
I checked inventory for potions and food:
I had 2 Chocolates that I was going to feed to my Shade Wolf. I also had a Meat and Milk.
I hatched a Desert Cactus first, then went to Stables to feed the wolf.
Now there was only 1 Chocolate.

**HabitRPG**          0.0.50
**Device**                    SGH-T999
**Android OS**          4.3
**Android Kernel**          3.0.31-1962493
**Android Build**          JSS15J.T999UVUENC2

**Comment by crookedneighbor** [comment]
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
