### ISSUE TITLE
Mobile App becomes unfunctional after editing task

### ISSUE THREAD

**Issue by mholmeslinder** [HabitRPG/habitrpg-mobile#367]
If I try to edit a task - change difficulty, add a checklist, etc. - in the mobile app, it seems to stop functioning/syncing. I no longer get a spinny wheel when I try to refresh, and anything else I change doesn't sync with the app/online version. This has been happening since I started using it (again) in November 2014.

**Comment by TheChumBucket** [comment]
I found a prevention to this problem. When you edit an item, make sure to open the Due Date option. If you don't want a due date, simply hit the Clear option, then save. If it already had a due date, you still need to open the menu, even if you select the same due date. This allowed me to edit through the mobile app and sync after the edit.

**Comment by crookedneighbor** [comment]
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
