### ISSUE TITLE
login information (username/password OR uuid/apikey) being requested every time I restart application on Android

### ISSUE THREAD

**Issue by cdepillabout** [HabitRPG/habitrpg-mobile#368]
Every time I restart my tablet (or force-kill HabbitRPG), I am asked to re-enter my username and password.  It looks like the username and password (or uuid/apikey?) are not being saved internally correctly?

After re-entering the username and password, I am able to login, see my tasks, etc.

I am using an Nexus 7 tablet, running Android Lollipop, 5.1.  The app was working correctly on my Nexus 5, but it is not working on Nexus 7.

**Comment by crookedneighbor** [comment]
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
