### ISSUE TITLE
Numbers text for gems, gold , and silver is slightly off from underneath images.

### ISSUE THREAD

**Issue by Rbrinkley** [HabitRPG/habitrpg-mobile#369]
Hello! I noticed this while I was looking for issues on the mobile app. 

The text for the amount of gems, gold, and silver is slightly left from being underneath the images. I took a screenshot and edited the image to show the part in question. 

I know it's a minor issue but just wanted to point it out. I am really bored in the class right now, we have nothing else to do. Thought it would be good to bug test and issue find. 

Thank you and have a great day.

![screenshot_2015-04-30-11-02-25-1](https://cloud.githubusercontent.com/assets/7588148/7417167/d8e78b50-ef29-11e4-94fd-a0c2c7a58a3b.jpg)

User ID:6f14571c-f2e9-4446-8e4e-591a7a3a42eb

**Comment by Rbrinkley** [comment]
Don't ask why the title said underage. my predictive keyboard doesn't know English and I don't even know why it changed it. Sorry about that.

**Comment by crookedneighbor** [comment]
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
