### ISSUE TITLE
Android: Task Menu Option shortened

### ISSUE THREAD

**Issue by ejwmoreau** [HabitRPG/habitrpg-mobile#370]
When the avatar picture on the side menu is a bit bigger than usual (I think because of pets/mounts), then the Task Menu Option is shrunk because of the overflowing avatar picture.

**Comment by crookedneighbor** [comment]
Would you mind posting a few screenshots?

**Comment by ejwmoreau** [comment]
Here are a few screenshots. I tried:
- Both Pets and Armor
- Only Armor
- No Armor or Pets

Couldn't manage to get it back to normal though. If you have any suggestions, I'll try it out.

On a Oneplus One, in case that helps.

![habitrpg - with pets](https://cloud.githubusercontent.com/assets/9069605/7554691/32e4d65a-f775-11e4-8af8-ecd72a0d91bb.png)

![habitrpg - with simple clothes](https://cloud.githubusercontent.com/assets/9069605/7554692/32e88408-f775-11e4-9d4f-e7fd36ad678b.png)

![habitrpg - with armor](https://cloud.githubusercontent.com/assets/9069605/7554693/32f272ba-f775-11e4-8f84-47e41eaf02c3.png)

**Comment by crookedneighbor** [comment]
Would you click on About and tell me what version of the app this is? I thought this issue was fixed already.

**Comment by ejwmoreau** [comment]
I've got version 0.0.50, and I can see on Play Store that the latest version is 0.0.51, though I can't seem to be able to update to that version.

**Comment by crookedneighbor** [comment]
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
