### ISSUE TITLE
New Update Problems

### ISSUE THREAD

**Issue by JBaby343** [HabitRPG/habitrpg-mobile#371]
I can no longer see my avatar, health, experience, or mana bars on the mobile app after the most recent update (2 days ago). I have a Motorola MOTO G phone. Everything works fine except the area where my character should be is grayed out. Thanks for your help in this matter.

**Comment by negue** [comment]
Could you provide a Screenshot? What Android Version Do you have? Are you using a custom rom?

**Comment by cochrane343** [comment]
I experience the same problem since the update on my OnePlus One with CyanogenMod.
My Android version is 4.4.4. I've attached a screenshot of the issue below:

![screenshot_issue_371](https://cloud.githubusercontent.com/assets/1556380/7896863/f86e6772-06c7-11e5-8815-f088ed19e85b.png)

**Comment by JBaby343** [comment]
I'm using Android version 4.4.4. I don't know what a custom rom is so I'm going to say no. This isn't my phone screen shot but the app looks the same. The only difference is the stuff at the top (time, notifications, etc. specific to the phone itself). Thank you for your assistance.





Date: Fri, 29 May 2015 21:38:09 -0700

**Comment by negue** [comment]
I was able to fix the avatar, but the icons for health/mana/exp and gems/gold don't to accept the avatar fix :/

**Comment by JBaby343** [comment]
I saw the change. Now I can see my avatar, health, exp, and mana but you're right no gold. That's ok though it still looks much better. Thank you for your help. I really appreciate it.
Best Regards,
Jason



Date: Tue, 9 Jun 2015 09:27:05 -0700

**Comment by crookedneighbor** [comment]
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
