### ISSUE TITLE
Invalid presets of datepicker for tasks without due date

### ISSUE THREAD

**Issue by cochrane343** [HabitRPG/habitrpg-mobile#372]
When editing a task on mobile, which has no due date yet, the datepicker on the edit view is pre-set with invalid values. [See here.](https://github.com/HabitRPG/habitrpg-mobile/blob/master/scripts/controllers/tasksCtrl.js#L20)

- In case the due date is null, the picker is pre-set with 1 January, 1970.
- In case the due date is undefined, the picker is pre-set with an invalid Date instance.

Possible solution:
- Only pre-set the datepicker with a Date instance, if task.date is a valid date.
- Remove invalid due dates before updating tasks.

**Comment by crookedneighbor** [comment]
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
