### ISSUE TITLE
Dailies mobile doubling and not finishing

### ISSUE THREAD

**Issue by arimakura** [HabitRPG/habitrpg-mobile#373]
http://imgur.com/xwDfqFg screenshot of issue of dailies doubling and not finishing turning red and i lose health or die. Id finish all dailies and when i select the last one it turns yellow or red again. I connected via pc last and they're still doubling. Tried sleeping in the inn for them to reset and they didnt.

Went onto pc and same problem. Here's screenshots in order; http://imgur.com/qIZmT4z
http://imgur.com/y5IoeLN
http://imgur.com/4Y49XqR

**Comment by crookedneighbor** [comment]
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
