### ISSUE TITLE
Cannot log in on android app

### ISSUE THREAD

**Issue by skeletorfw** [HabitRPG/habitrpg-mobile#376]
HabitRPG version: 0.0.55
Android 5.0.2 - Moto G 1st gen

When logging in, my username/email and password come up as incorrect.
These same details do however log me in to the main site.

**Comment by BornLuna** [comment]
the username & password are both case sensitive

**Comment by BornLuna** [comment]
@skeletorfw the username & password are both case sensitive

**Comment by crookedneighbor** [comment]
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
