### ISSUE TITLE
Missing spells

### ISSUE THREAD

**Issue by mistermocha** [HabitRPG/habitrpg-mobile#388]
Platform: Nexus 5, Android v5.1.1
App Version: 0.0.59

Forgive me if this is the wrong place to report this... Under 'Tasks' is where I should see spells, but I do not. My spells show up on the desktop/mobile websites just fine.

**Comment by crookedneighbor** [comment]
I'm closing this because we're currently working on native apps and will not be adding any new features to the phonegap app.

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)
