### ISSUE TITLE
Android party fails to show the party at all

### ISSUE THREAD

**Issue by mistermocha** [HabitRPG/habitrpg-mobile#389]
This started today. Haven't updated recently so it's probably something server side. The mobile app fails to show my party. The website does show my party properly.

**Comment by crookedneighbor** [comment]
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)

**Comment by mistermocha** [comment]
Awesome. I'll hang tight for the next one then. Thanks!
